### ISSUE TITLE
Add different Python Versions to travis in Readme.md

### ISSUE THREAD

**Issue by DeastinY** [DeastinY/CoffeeRecommendationBot#19]

**Comment by meetmangukiya** [comment]
Can you please ellaborate? Which version? And to `.travis.yml` or `README.md`  ?

**Comment by QzSG** [comment]
@DeastinY Hopefully this is what you meant #20

If by adding different python versions you meant make travis test the build using travis you would need to add the following if u want `2.7` and `3.3`

``` yml
language: python

python:
  - 2.7
  - 3.3

install:
  - pip install -r requirements.txt
  - pip install pep8 flake8
  - pip list

script:
  - flake8 .
```

If you need it ill make the changes
